version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,BROKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,BROKER://0.0.0.0:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:14
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: payment_db
      POSTGRES_INITDB_ARGS: "--auth-host=trust"
    volumes:
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: ["postgres", "-c", "wal_level=replica", "-c", "max_wal_senders=10", "-c", "hot_standby=on", "-c", "listen_addresses=*", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]

  postgres-replica1:
    image: postgres:14
    hostname: postgres-replica1
    depends_on:
      - postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: payment_db
    volumes:
      - postgres_replica1_data:/var/lib/postgresql/data
    user: "postgres"
    command: ["/bin/bash", "-c", "chown -R postgres:postgres /var/lib/postgresql/data && chmod 700 /var/lib/postgresql/data && until pg_isready -h postgres -p 5432 -U example; do echo waiting for postgres; sleep 2; done; rm -rf /var/lib/postgresql/data/*; pg_basebackup -h postgres -p 5432 -U example -D /var/lib/postgresql/data -F p -Xs -P -R; postgres -c 'hot_standby=on'"]

  postgres-replica2:
    image: postgres:14
    hostname: postgres-replica2
    depends_on:
      - postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: payment_db
    volumes:
      - postgres_replica2_data:/var/lib/postgresql/data
    user: "postgres"
    command: ["/bin/bash", "-c", "chown -R postgres:postgres /var/lib/postgresql/data && chmod 700 /var/lib/postgresql/data && until pg_isready -h postgres -p 5432 -U example; do echo waiting for postgres; sleep 2; done; rm -rf /var/lib/postgresql/data/*; pg_basebackup -h postgres -p 5432 -U example -D /var/lib/postgresql/data -F p -Xs -P -R; postgres -c 'hot_standby=on'"]

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  postgres_replica1_data:
  postgres_replica2_data:
