version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,BROKER://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:14
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: payment_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-replica1:
    image: postgres:14
    hostname: postgres-replica1
    depends_on:
      - postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: payment_db
    volumes:
      - postgres_replica1_data:/var/lib/postgresql/data
    command: ["-c", "host=postgres user=example password=example dbname=payment_db replication=true"]

  postgres-replica2:
    image: postgres:14
    hostname: postgres-replica2
    depends_on:
      - postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: payment_db
    volumes:
      - postgres_replica2_data:/var/lib/postgresql/data
    command: ["-c", "host=postgres user=example password=example dbname=payment_db replication=true"]

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  postgres_replica1_data:
  postgres_replica2_data:
